/* This file was generated by the "svnrev" utility
 * (http://www.compuphase.com/svnrev.htm).
 * You should not modify it manually, as it may be re-generated.
 *
 * $Revision: 483$
 * $Date: 2009-05-29$
 */

#ifndef SVNREH_H
#define SVNREV_H

#define SVN_REV		483
#define SVN_REVSTR	"483"
#define SVN_REVDATE	"2009-05-29"
#define SVN_REVSTAMP	20090529L
#define SVN_MODIFIED	0

#endif /* SVNREV_H */
